version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: video-downloader-proxy
    ports:
      - "62284:62284"
    volumes:
      - ./data:/data
